# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logregis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Not Available', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Not Available', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='Not Available'),
        ),
    ]
