# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logregis', '0003_author_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
