# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logregis', '0004_auto_20170125_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
